zooniverse/alice

src/App.js, src/components/Badge/Badge.js, src/components/EditorHeader/EditorHeader.js, src/components/ResourcesTable/ResourcesTable.js, src/screens/Home/Home.js, src/screens/Home/components/InfoText.js, src/screens/Home/components/Label/Label.js, src/screens/Home/components/Label/index.js, src/screens/Home/components/LoginForm/LoginForm.js, src/screens/Home/components/LoginForm/LoginFormContainer.js, src/theme.js
This PR addresses some items items still remaining from #2.
=> Follow Up Initial Layout Merge

src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js, src/components/LineViewer/LineViewer.stories.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/components/TranscriptionLine.js, src/components/LineViewer/components/theme.js, src/components/LineViewer/index.js, src/components/LineViewer/mockLines.js, src/components/LineViewer/theme.js, src/helpers/indexToColor.js, src/helpers/withThemeContext/index.js, src/helpers/withThemeContext/withThemeContext.js
This PR adds non-functioning components for the transcription line viewer. Open storybook to view the `LineViewer` story.
=> Add Transcription Viewer Components

src/App.js, src/components/EditorHeader/EditorHeader.js, src/components/EditorHeader/EditorHeader.spec.js, src/components/EditorHeader/EditorHeaderContainer.js, src/components/EditorHeader/EditorHeaderContainer.spec.js, src/components/EditorHeader/components/HeaderButton/DownloadSetDataContainer.js, src/components/EditorHeader/components/HeaderButton/DownloadSetDataContainer.spec.js, src/components/EditorHeader/components/HeaderButton/LayoutButtonContainer.js, src/components/EditorHeader/components/HeaderButton/SearchButtonContainer.js, src/components/EditorHeader/components/HeaderButton/SearchButtonContainer.spec.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.js, src/components/ResourcesTable/ResourcesTable.js, src/paths.js, src/screens/ProjectsIndex/ProjectsIndexPage.js, src/screens/ProjectsIndex/ProjectsPageContainer.js, src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.js, src/screens/ProjectsIndex/mockProjects.js, src/screens/SubjectSetsIndex/mock.js, src/screens/SubjectsIndex/mock.js, src/screens/WorkflowsIndex/mockWorkflowData.js, src/store/AuthStore.js
This PR changes which header tools are shown depending on the path given. I've also added tests for the components I touched. I've help off adding functionality here using a mobx store until #16 is merged with the `ImageStore`. I'll add button functions in a separate PR.
[Edit page layout](https://projects.invisionapp.com/d/?origin=v7?origin=v7#/console/17925240/371813754/preview)
[Subjects Page layout](https://projects.invisionapp.com/d/?origin=v7?origin=v7#/console/17925240/375544496/preview)
=> Add Header Tools by Path

.storybook/webpack.config.js, src/components/SubjectViewer/SubjectViewer.js, src/components/SubjectViewer/SubjectViewerContainer.js, src/components/SubjectViewer/components/ImageTools/ImageTools.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/ResetButton.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/ResetButton.spec.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/ResetButtonContainer.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/ResetButtonContainer.spec.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/index.js, src/components/SubjectViewer/components/ImageTools/components/RotateButton/RotateButton.js, src/components/SubjectViewer/components/ImageTools/components/RotateButton/RotateButtonContainer.js, src/components/SubjectViewer/components/ImageTools/components/ZoomInButton/ZoomInButton.js, src/components/SubjectViewer/components/ImageTools/components/ZoomInButton/ZoomInButtonContainer.js, src/components/SubjectViewer/components/ImageTools/components/ZoomOutButton/ZoomOutButton.js, src/components/SubjectViewer/components/ImageTools/components/ZoomOutButton/ZoomOutButtonContainer.js, src/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js, src/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.js, src/components/SubjectViewer/components/InteractionLayer/InteractionLayerContainer.spec.js, src/store/AppStore.js, src/store/AuthStore.js, src/store/ImageStore.js, src/store/ImageStore.spec.js
This pr adds functionality for all image tools you can view by hovering over a subject. You can test these in storybook. I also added a refresh button and tests.
=> Add Image Tool Functionality

src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.spec.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.stories.js, src/components/EditorHeader/components/MetadataButton/MetadataButtonContainer.js, src/components/EditorHeader/components/MetadataButton/MetadataButtonContainer.spec.js, src/components/EditorHeader/components/MetadataButton/index.js, src/components/EditorHeader/components/MetadataButton/mockMetadata.js
Pretty straightforward PR to introduce the clickable "i" button to display subject metadata.
[InVision Design](https://projects.invisionapp.com/d/?origin=v7?origin=v7#/console/17925240/371813754/preview)
=> Metadata Button

.travis.yml, README.md, package.json, yarn.lock
Closes #44 
This PR sets up Travis and Coveralls with README badges
=> Setup travis

.travis.yml, package.json
Coveralls wasn't working as it needed, so I made a few adjustments here.
=> Adjust Coveralls Config

.storybook/config.js, package.json, src/Storyshots.test.js, src/__snapshots__/Storyshots.test.js.snap, src/components/ZoomInButtonContainer.js, yarn.lock
This is low priority. I noticed all `.stories` files were not included in testing coverage, which irritated me. I've added snapshots to these, which is the [preferred way](https://storybook.js.org/docs/testing/structural-testing/) to do Storybook testing.
=> Include .stories in Testing

package.json, src/App.js, src/App.test.js, src/screens/ProjectsIndex/ProjectsPageContainer.js, src/screens/ProjectsIndex/ProjectsPageContainer.spec.js, src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.js, src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.spec.js, src/store/AppStore.js, src/store/ClientStore.js, src/store/ProjectsStore.js, src/store/ProjectsStore.spec.js, src/store/factories/project.js, yarn.lock
This PR begins fetching projects from the TOVE backend. Currently, all projects are being returned from Tove as there are only a few in the database. Later, this will be changed to returning only those projects for the logged in user.
=> Fetch Projects

package.json, src/__snapshots__/Storyshots.test.js.snap, src/components/AggregationSettings/AdjustReducer.js, src/components/AggregationSettings/AggregationSettings.js, src/components/AggregationSettings/AggregationSettings.spec.js, src/components/AggregationSettings/AggregationSettings.stories.js, src/components/AggregationSettings/AggregationSettingsContainer.js, src/components/AggregationSettings/AggregationSettingsContainer.spec.js, src/components/AggregationSettings/ChooseReducer.js, src/components/AggregationSettings/ChooseReducer.spec.js, src/components/AggregationSettings/Confirmation.js, src/components/AggregationSettings/Confirmation.spec.js, src/components/AggregationSettings/DBScanReducer.js, src/components/AggregationSettings/DBScanReducer.spec.js, src/components/AggregationSettings/OpticsReducer.js, src/components/AggregationSettings/OpticsReducer.spec.js, src/components/AggregationSettings/index.js, yarn.lock
Closes #31 
This PR creates the modal to display aggregation settings forms. Tests are also included for new components. This PR handles all of the form styling and navigation within the modal, but the forms are currently only available on storybook. To keep this PR from becoming too bloated, displaying the forms in the UI will come in a separate PR.
=> Aggregation forms

package.json, src/screens/Editor/components/Resizer.js, src/screens/Editor/components/Resizer.spec.js, src/store/AuthStore.js, src/store/AuthStore.spec.js, src/store/EditorStore.spec.js, src/store/SubjectStore.js, src/store/SubjectStore.spec.js, yarn.lock
This PR creates several tests, mainly those for the `Resizer` component as well as the missing store tests.
=> Create Missing Tests

src/components/FilmstripViewer/components/StepNavigation/StepNavigation.js, src/components/FilmstripViewer/components/StepNavigation/StepNavigation.spec.js, src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js, src/screens/Home/components/LoginForm/LoginForm.spec.js, src/store/SubjectStore.js, src/store/SubjectStore.spec.js, src/store/factories/subject.js
This PR adds missing tests for:
=> Add Missing Tests

src/__snapshots__/Storyshots.test.js.snap, src/components/Badge/Badge.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.js, src/components/Modals/DownloadDataModal/DownloadDataModal.js, src/components/Modals/SubjectLockedModal/SubjectLockedModal.js, src/components/Modals/UnapproveModal/UnapproveModal.js, src/components/SearchModal/SearchModal.js, src/components/SubjectViewer/components/ImageTools/components/ResetButton/ResetButton.js, src/components/SubjectViewer/components/ImageTools/components/RotateButton/RotateButton.js, src/components/SubjectViewer/components/ImageTools/components/ZoomInButton/ZoomInButton.js, src/components/SubjectViewer/components/ImageTools/components/ZoomOutButton/ZoomOutButton.js, src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.js, src/theme.js
Most of the changes here include improving the contrast of background/foreground colors and adding some alt text for screen readers. Changes here are to improve Lighthouse audits on the JS toolbar.
=> Simple Accessibility Improvements

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/AggregatedTranscriptions.js, src/components/AggregatedTranscriptions/AggregatedTranscriptions.spec.js, src/components/AggregatedTranscriptions/AggregatedTranscriptionsContainer.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/Flags.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableContainer.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableContainer.spec.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.spec.js, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/components/TranscriptionLine.js, src/screens/Editor/Editor.js, src/screens/Editor/components/Resizer.js, src/store/AggregationsStore.js, src/store/AggregationsStore.spec.js
This PR opens the transcription pane when clicking on a transcription to the right. Check out the [InVision](https://projects.invisionapp.com/d/#/console/17925240/371813757/preview). I had to move around some of the elements padding and margins so this would appear to "overflow" the parent.
**Note**: Most of the line changes here are updating the snapshots.
=> Open transcription panel

src/components/ResourcesTable/ResourcesTable.js, src/components/StepNavigation/StepNavigation.js, src/screens/Editor/Editor.js
Margins on the filmstrip viewer were a bit off, so this helps sort things out.
=> Adjust Filmstrip Margins

src/App.js, src/store/AuthStore.js, src/store/AuthStore.spec.js, src/store/ClientStore.js, src/store/ClientStore.spec.js
This PR handles setting the JWT token for TOVE authentication. There's still some thought that needs to go into the two hour timeline, that I've explained a bit in #82 
However, the app is currently broken without setting the JWT token, so I'm making these changes now.
=> Handling auth

src/screens/Home/components/LoginForm/LoginForm.js
=> Fix Overlapping Errors

src/__snapshots__/Storyshots.test.js.snap, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/LineViewer/components/TranscriptionLine.js, src/components/LineViewer/theme.js, src/store/Reduction.js
This PR covers many of the UI issues found in the review of #78. However, I'm holding off on the issue of the checkbox being too small for a later UI audit, as that is worth a longer discussion.
=> Transcription Pane Improvements

src/__snapshots__/Storyshots.test.js.snap, src/components/FilmstripViewer/FilmstripViewerContainer.js, src/components/FilmstripViewer/FilmstripViewerContainer.spec.js, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/components/DeleteModal/DeleteModal.js, src/components/LineViewer/components/DeleteModal/DeleteModal.spec.js, src/components/LineViewer/components/DeleteModal/DeleteModalContainer.js, src/components/LineViewer/components/DeleteModal/DeleteModalContainer.spec.js, src/components/LineViewer/components/DeleteModal/index.js, src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
This PR handles deleting an annotation line and saves the transcription on deletion. Be careful with this, as it is currently irreversible. I'd like to get #89 merged first so I can clean up some code in the `LineViewerContainer` to get testing up. 
[Invision Design](https://projects.invisionapp.com/share/KBVXAK04S2C#/screens)
Working towards #33
=> Delete Transcription Lines

package.json, src/components/EditorHeader/components/MarkApproved/MarkApproved.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.spec.js, src/components/EditorHeader/components/MarkApproved/MarkApprovedContainer.js, src/components/EditorHeader/components/MarkApproved/MarkApprovedContainer.spec.js, src/store/ProjectsStore.js, src/store/ProjectsStore.spec.js, src/store/TranscriptionsStore.js, yarn.lock
Closes #98 
Mainly just a change in terminology. This is to avoid the former confusion where a user with a PFE role of "researcher" was not given the "researcher" role in ALICE.
=> Adjust Role Titles to Use Admin and Editor

.gitignore, README.md, package.json, src/config.js, src/store/ClientStore.js, src/store/SubjectStore.js, src/store/SubjectStore.spec.js, src/store/TranscriptionsStore.js, yarn.lock
I'm utilizing `react-scripts` here to handling building the app, then appending the correct path `alice.zooniverse.org` for deployment and `preview.zooniverse.org/alice` (alice.preview.zooniverse.org) for staging to send the site to the S3 bucket with `publisssh`. 
I've also created a `config.js` file to handle URLs that must dynamically change depending on the environment.
Closes #94
=> Deploy App Using React Scripts

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableContainer.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableContainer.spec.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js, src/components/EditorHeader/EditorHeaderContainer.js, src/components/EditorHeader/EditorHeaderContainer.spec.js, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/LineViewer/components/FlagButtons/FlagButton.js, src/components/LineViewer/components/FlagButtons/FlagButton.spec.js, src/components/LineViewer/components/FlagButtons/FlagButtonContainer.js, src/components/LineViewer/components/FlagButtons/SeenButtonContainer.js, src/components/LineViewer/components/TranscriptionLine.js, src/screens/Editor/Editor.spec.js, src/store/ProjectsStore.js, src/store/ProjectsStore.spec.js
This PR handles the different layout you would expect to see for all roles: Admin, Editor, and Viewer. You can find the user stories [here](https://docs.google.com/document/d/1tWyQ9e9vJu9usIJlrPSAw8f3_L65Iz2ysVnFnbOMmWM/edit).
The main differences are:
- **Admin:** Full access with marking subject "approved"
- **Editor:** Full access with marking subject "ready"
- **Viewer:** Limited access. Unable to edit a transcription or download data sets
Closes #81
=> Role Permissions

src/__snapshots__/Storyshots.test.js.snap, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPane.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPane.spec.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.spec.js
Closes #109 
This PR allows clicking on a reduction line to [open that line in the annotation panel](https://projects.invisionapp.com/d/#/console/17925240/371813757/preview).
=> Click Line to Open

src/__snapshots__/Storyshots.test.js.snap, src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.spec.js, src/components/EditorHeader/components/MetadataButton/theme.js
This PR handles some issues with the metadata modal UI. Closes #122
=> Reorganize Metadata Content

src/store/ClientStore.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
With recent model locking updates to TOVE (https://github.com/zooniverse/tove/pull/151, https://github.com/zooniverse/tove/pull/171), ALICE now needs to send the last updated time along with each patch. 
This PR is mainly a fix to get patching working again. Another PR with all the model locking bells and whistles will follow.
=> Send If-modified-since Headers

src/screens/Home/Home.js, src/screens/Home/components/Footer/Footer.js, src/screens/Home/components/InfoText.js, src/screens/Home/components/LoginForm/LoginForm.js, src/screens/Home/homeContent.js
This PR makes some changes to the home page. Changes should account for different page views with a window width < 768px and > 1440px. See more detail on the attached issues.
Closes #119 
Fixes "Login Page" section from #110
=> Home Design Notes

package.json, src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/AggregatedTranscriptions.js, src/components/AggregatedTranscriptions/AggregatedTranscriptionsContainer.js, src/components/AggregatedTranscriptions/AggregatedTranscriptionsContainer.spec.js, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/LineViewer/components/FlagButtons/FlagButton.js, src/components/LineViewer/components/FlagButtons/FlagButton.spec.js, src/helpers/parseTranscriptionData.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
This PR gives functionality to the "Add Line" buttons both when a transcription is selected and on the main editor page (see [InVision](https://projects.invisionapp.com/d/#/console/17925240/371813757/preview)). 
When [adding a new transcription](https://projects.invisionapp.com/d/#/console/17925240/401676674/preview), when a user does not input text: 
- Closing the panel should delete the transcription
- Adding a line should be disabled
- The "seen" and "flagged" flags should be disabled
After inputting text, the new line will behave as the other lines.
This PR will close #33
=> Add Line Function

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js, src/components/AggregationSettings/ChooseReducer.js, src/components/AggregationSettings/OpticsReducer.js, src/components/Badge/Badge.js, src/components/EditorHeader/components/MetadataButton/theme.js, src/components/LineViewer/components/FlagButtons/FlagButton.js, src/components/LineViewer/theme.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.js, src/screens/Editor/components/Resizer.js, src/theme.js
Closes #141 
This PR uses the styled-components CSS helpers to avoid an issue with memory leaks.
=> Use CSS Helpers to Avoid Memory Leaks

src/screens/Home/homeContent.js, src/store/AuthStore.js, src/theme.js
Closes #147 
This PR adjusts the help text and links on the home page. It also allows a user to visit the '/about' page without being logged in, which was previously a bug.
=> Adjust Home Text Blurbs

src/components/Badge/Badge.js, src/components/Badge/Badge.spec.js
Addresses badge issues mentioned in #151, namely:
- Increases size of each link/button
- Closes the Badge drop/nav after click
- Tests that drop is closed with a click
=> Badge Updates

.github/workflows/deploy_staging.yml
Adds the Deploy Staging github action. Use yarn to build and deploy, and setting REACT_APP_ENV for the latter. Then notify slack.
=> Add Deploy Staging Action

public/index.html
Replace the index HTML page while maintenance is under way.
=> Add a maintenance message

README.md, package.json, yarn.lock
Remove old scripts for publishing to S3.
=> Remove old deploy scripts. Update readme

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
=> Revert "Specify content-type of text/html files"

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
=> Revert "Typo: add missing backslashes"

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
=> Revert "Include newly-required --overwrite flag in az uploads"

package.json, yarn.lock
Bump yup to latest. Includes a critical fix for `property-expr`.
=> [Security] Upgrade yup

package.json, yarn.lock
Bump all the `@storybook` packages to 5.3.21.
=> Upgrade storybook to 5.3

src/components/AggregatedTranscriptions/AggregatedTranscriptions.stories.js, src/components/AggregationSettings/AggregationSettings.stories.js, src/components/EditorHeader/components/HeaderButton/HeaderButtons.stories.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.stories.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.stories.js, src/components/FilmstripViewer/FilmstripViewer.stories.js, src/components/LineViewer/LineViewer.stories.js, src/components/Modals/DownloadDataModal/DownloadDataModal.stories.js, src/components/Modals/SubjectLockedModal/SubjectLockedModal.stories.js, src/components/Modals/UnapproveModal/UnapproveModal.stories.js, src/components/SearchModal/SearchModal.stories.js, src/components/SubjectViewer/SubjectViewerContainer.stories.js
Convert all the stories to CSF, using [`storiesof-to-csf`](https://github.com/storybookjs/storybook/tree/main/lib/codemod#storiesof-to-csf).
=> Convert stories to CSF

package.json, yarn.lock
This is an update to PJC, for security reasons.
=> Update panoptes-client to 4.1.0
