.storybook/config.js, package.json, src/App.js, src/components/EditorHeader/components/HeaderButton/HeaderButton.js, src/components/EditorHeader/components/HeaderButton/HeaderButtons.stories.js, src/components/EditorHeader/components/HeaderButton/LayoutButtonContainer.js, src/components/EditorHeader/components/HeaderButton/LayoutButtonContainer.spec.js, src/components/EditorHeader/components/HeaderButton/MoreButtonContainer.js, src/components/EditorHeader/components/HeaderButton/MoreButtonContainer.spec.js, src/components/EditorHeader/components/HeaderButton/SaveButtonContainer.js, src/components/EditorHeader/components/HeaderButton/SaveButtonContainer.spec.js, src/components/EditorHeader/components/HeaderButton/UndoButton.spec.js, src/components/EditorHeader/components/HeaderButton/UndoButtonContainer.js, src/components/EditorHeader/components/HeaderButton/UndoButtonContainer.spec.js, src/components/EditorHeader/components/HeaderButton/index.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.spec.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.stories.js, src/components/EditorHeader/components/MarkApproved/MarkApprovedContainer.js, src/components/EditorHeader/components/MarkApproved/index.js, src/components/FilmstripViewer/FilmstripViewer.js, src/components/FilmstripViewer/FilmstripViewer.stories.js, src/theme.js, yarn.lock
This PR introduces a `HeaderButton` functional component to render all buttons to be used in the header. I am using Font Awesome again because grommet-icons is lacking and I the package allows me to rotate icons with a prop (needed for the layout button). 
All buttons are visible in the storybook `yarn storybook`
=> Introduce HeaderButton Component and Containers

src/components/AggregatedTranscriptions/AggregatedTranscriptions.js, src/components/AggregatedTranscriptions/AggregatedTranscriptions.stories.js, src/components/AggregatedTranscriptions/AggregatedTranscriptionsContainer.js, src/components/EditorHeader/components/HeaderButton/LayoutButtonContainer.js, src/components/SubjectViewer/SubjectViewerContainer.js, src/screens/Editor/Editor.js, src/screens/Editor/components/Resizer.js, src/store/AppStore.js, src/store/ClassifierStore.js, src/store/EditorStore.js
This PR adds two controls to the classifier. 
- Allow users to switch between landscape modes using the header button
- Allow users to change widths and heights of the subject and transcription viewers using the ellipsis drag handler.
[Editor page design](https://projects.invisionapp.com/d/?origin=v7?origin=v7#/console/17925240/371813754/preview)
Closes #34
=> Add Classifier Layout Controls

.storybook/webpack.config.js
Whoops! Jumping two major Storybook versions in [this PR](https://github.com/zooniverse/text-editor/pull/43) caused some breaking issues I was unaware of. 
From the official docs, [this](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-config-simplification) was the breaking change (webpack config simplification).
=> Change config object

src/components/EditorHeader/components/HeaderButton/DownloadSetDataContainer.js, src/components/ResourcesTable/ResourcesTable.js, src/components/ResourcesTable/ResourcesTable.spec.js
This PR removes checkboxes from the resources table as they're no longer needed [per InVision](https://projects.invisionapp.com/d/#/console/17925240/375544496/preview). I also updated the phrasing of the subject set download button above as that was the original impetus for the change.
=> Remove Checkboxes from ResourcesTable

src/components/EditorHeader/components/Title/Title.js
We've changed the way we route the header title to save space for longer names and routes. See the "Projects / Project Name / Workflow Name" [here](https://projects.invisionapp.com/d/#/console/17925240/375544496/preview). 
You won't see the "Projects" addition in this PR as the first subheader, since that functionality has been added to #65 
Closes #64
=> Change Title Header to Save Space

src/store/AuthStore.js, src/store/AuthStore.spec.js
In making some changes to #67, I realized the logout function wasn't actually resetting forgetting the user within the app.
=> Allow SignOut function to Reset User

src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Fixes a TODO from when TOVE did not have a one to one relationship between transcription ids and Panoptes subjects. Because of this, the app originally looked for transcriptions associated with a particular subject. However, with the change, a `/transcriptions/id` route now exists, and Alice can hit that endpoint and expect to receive one object instead of an array.
Merging this now as the app is currently breaking without the fix.
=> Fetch Single Transcription Bug

src/__snapshots__/Storyshots.test.js.snap, src/components/ResourcesTable/ResourcesTable.js, src/components/ResourcesTable/ResourcesTable.spec.js, src/components/ResourcesTable/components/SearchTags/SearchTag.js, src/components/ResourcesTable/components/SearchTags/SearchTag.spec.js, src/components/ResourcesTable/components/SearchTags/SearchTagContainer.js, src/components/ResourcesTable/components/SearchTags/SearchTagContainer.spec.js, src/components/ResourcesTable/components/SearchTags/index.js, src/components/SearchModal/SearchModal.js, src/components/SearchModal/SearchModal.spec.js, src/components/SearchModal/SearchModalContainer.js, src/components/SearchModal/SearchModalContainer.spec.js, src/screens/SubjectsIndex/SubjectsPageContainer.js, src/screens/SubjectsIndex/SubjectsPageContainer.spec.js, src/screens/SubjectsIndex/table.js, src/store/AppStore.js, src/store/SearchStore.js, src/store/SearchStore.spec.js, src/store/TranscriptionsStore.js
This is WIP because we're still waiting on a couple items before this is ready.
Closes #21 
1) Waiting for #68 to merge because I'll have to keep track of the current query when paginating. What if somebody has an active search filter? They'll want to retain that filter when paginating.
2) There are several items that aren't yet filterable on the Tove end (`internal_id`, `low_consensus_score`, filtering by status string instead of enum integer).
=> Search Modal Functions

src/screens/SubjectsIndex/table.js, src/store/AppStore.spec.js, src/store/TranscriptionsStore.js
Due to a recent change in [how we serialize the text object](https://github.com/zooniverse/tove/pull/135), the index page was no longer loading without text objects. This PR should fix that issue.
A later backend change is coming which will allow items once held in the text object (consensus score, transcribed lines, and pages) to be pulled from the transcription object.
=> Allow Transcriptions Index Page to Load Without Text Object

src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Closes #102 
This PR adds the current workflow ID to the query when fetching for transcriptions. This will help the backend more accurately return relevant transcriptions.
=> Add Workflow Id to Transcriptions Query

package.json, src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/LineViewer/components/TranscriptionLine.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.js, src/helpers/parseTranscriptionData.js, src/helpers/parseTranscriptionData.spec.js, src/helpers/writeDate.js, src/store/Reduction.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Closes #90 
In attempting to save the original transcriber, I had to do more mapping of extracts and reductions. In doing so, I found many opportunities for refactoring. This PR refactors many of those mapping functions while also rewriting the `TranscriptionsStore` tests as they were getting a bit unwieldy and needed to be straightened up some.
=> Refactor and Save Original Transcriber

src/store/Reduction.js
The `user_ids` array contains integers when coming from TOVE, but strings when reextracting. This PR adds some variability when storing those values
=> Allow user_ids array to be string or integer

package.json, src/__snapshots__/Storyshots.test.js.snap, src/components/Modals/DownloadDataModal/DownloadDataModal.js, src/components/Modals/DownloadDataModal/DownloadDataModalContainer.js, src/components/Modals/DownloadDataModal/DownloadDataModalContainer.spec.js, src/store/ClientStore.js, src/store/ClientStore.spec.js, yarn.lock
Closes #25 
Hooks up the UI to allow downloading group exports on the [transcriptions page](https://projects.invisionapp.com/d/#/console/17925240/375544496/preview) and single transcriptions on the [edit page](https://projects.invisionapp.com/d/#/console/17925240/371813753/preview).
- Downloading subject set data should download all approved subjects in a subject group into a .zip.
- Downloading a single subject from the edit page will also download a .zip for that individual subject.
**Note**: Transcription must be marked "approved" to download export
=> Data downloads

src/components/SubjectViewer/SubjectViewerContainer.js, src/components/SubjectViewer/components/SVGView/SVGViewContainer.js, src/components/SubjectViewer/components/SVGView/SVGViewContainer.spec.js, src/screens/Editor/Editor.js, src/store/SubjectStore.js
Closes #118 
Three main items are fixed here:
**Set the image width and height when changing subjects**: This resolves an error when seeing a valid subject, visiting an invalid subject and seeing nothing, and returning to a valid subject where you would still see the 0x0 dimensions from the invalid subject.
**Allow async state to render while loading image**: This previously wasn't visible unless a user hovered over the SVG image container.
**Clear out the previous subject when loading a new one**: Previously, the previous subject would be visible for a moment when visiting a new subject
=> Fix UI Inconsistencies when Toggling Between Subjects

src/__snapshots__/Storyshots.test.js.snap, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPane.js, src/components/SubjectViewer/components/SVGView/SVGView.js, src/components/SubjectViewer/components/SVGView/SVGView.spec.js, src/components/SubjectViewer/components/SVGView/SVGViewContainer.js
Closes #134
Fixes an issue with a subject image not appearing the second time a user attempts the access it. Also fixes a bug with extract lines not appearing.
=> Show Subject on Second Access

src/store/TranscriptionsStore.js
Closes #120 
This PR takes care of an issue that emerged from a PR review. Transcription rows were being arranged without reparsing the order of the extracts, which accounts for displaying a user's transcription when the modal is open.
=> Reparse Extracts after Rearranging

src/__snapshots__/Storyshots.test.js.snap, src/components/LineViewer/LineViewer.js
Closes #115 
Takes care of issues with the transcription pane when too many transcriptions present. You can test this by going to a transcription with too many annotations for a line. 
This one should work:
**Project**: Anti-Slavery Testing
**Workflow**: Anti-Slavery Workflow 1
**Group**: TEST1
**Transcription**: 72815
Upon opening that transcription there should be a line on the table with 39 transcriptions that begins, "Mr that Oakes"
=> Add Minimum Heights to Transcription Sections

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/AggregatedTranscriptions.js, src/components/Badge/Badge.js, src/components/EditorHeader/components/HeaderButton/UndoButtonContainer.js, src/components/EditorHeader/components/MarkApproved/theme.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/MoreButton/MoreButton.js, src/components/EditorHeader/components/MoreButton/MoreButton.spec.js, src/components/EditorHeader/components/Title/Title.js, src/components/EditorHeader/components/Title/Title.spec.js, src/components/FilmstripViewer/FilmstripViewer.js, src/components/SubjectViewer/components/ImageTools/ImageTools.js, src/components/SubjectViewer/components/SubjectViewerHeader/SubjectViewerHeader.js, src/theme.js
This PR takes care of remaining items in the "Main Interface" and "Original Subject" section of #110. **Note:** I'm not too worried about the test coverage decreasing here as it's minimal and could also be contributed to removing lines from some refactoring in this PR.
- Adjusted to image tools background and order (Fig. 2)
- Added an "X" and check mark on the mark as approved button
- Switched the up and down arrows for drop buttons
- Changed the font size for header buttons
Fig 1:
Fig 2:
=> Interface Design Notes

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/AggregatedTranscriptionsContainer.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js, src/components/Badge/BadgeContainer.js, src/components/Badge/BadgeContainer.spec.js, src/components/EditorHeader/EditorHeaderContainer.js, src/components/EditorHeader/components/HeaderButton/UndoButtonContainer.js, src/components/EditorHeader/components/MarkApproved/MarkApproved.js, src/components/EditorHeader/components/MarkApproved/MarkApprovedContainer.js, src/components/EditorHeader/components/MetadataButton/MetadataButtonContainer.js, src/components/EditorHeader/components/MoreButton/MoreButtonContainer.js, src/components/EditorHeader/components/Title/Title.js, src/components/FilmstripViewer/FilmstripViewerContainer.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/LineViewer/components/TranscriptionLine.js, src/components/LineViewer/theme.js, src/components/SubjectViewer/SubjectViewerContainer.js, src/components/SubjectViewer/components/SubjectViewerHeader/SubjectViewerHeader.js, src/components/SubjectViewer/components/SubjectViewerHeader/SubjectViewerHeaderContainer.js, src/components/SubjectViewer/components/SubjectViewerHeader/SubjectViewerHeaderContainer.spec.js, src/screens/Editor/Editor.js, src/store/TranscriptionsStore.js
Handles the "Transcribed Line Detail" and "Transcription Lines" items from issue #110 
- Enlarged the text input box
- Removed the bullets between user time, date, and username (when shown) of transcriptions
- Disabled all buttons when a transcription is open (when modal in image is open)
- Adjust spacing of each transcription on the modal
- Adjusted spacing between "flag" and "consensus text"
=> Transcription Design Notes

src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.spec.js, src/components/FilmstripViewer/components/FilmstripThumbnail/ThumbnailBorder.js, src/components/FilmstripViewer/components/FilmstripThumbnail/ThumbnailBorder.spec.js
Takes care of the "All Pages" (Filmstrip Viewer) notes from #110 
- Capitalized the word "Pages" in the filmstrip viewer
- Adjusted the border of the filmstrip viewer
- Added hover states to the page images
=> Filmstrip Design Notes

src/__snapshots__/Storyshots.test.js.snap, src/components/Badge/Badge.js, src/components/Badge/Badge.spec.js, src/components/SearchModal/components/SearchCheckBox.js, src/components/SearchModal/components/SearchCheckBox.spec.js, src/components/SearchModal/components/theme.js, src/screens/SubjectsIndex/SubjectsPageContainer.js, src/screens/WorkflowsIndex/WorkflowsPageContainer.js, src/screens/WorkflowsIndex/WorkflowsPageContainer.spec.js, src/store/TranscriptionsStore.js, src/theme.js
Covers all items in the Indexes section of #110 ("General" and "Search/Filter"). **Note:** I'm not too worried about the test coverage decreasing here as it's minimal and could also be contributed to removing lines from some refactoring in this PR.
Closes #110 
- Adjust size of checkboxes
- Adjust the padding around username badge
- Persist search filters when going back to the transcriptions page. Ex: Let's say you are filtering or searching subjects on the subjects index page and then you select a subject/transcription to view in the editor. Once you're on the editor page, you should be able to press the group name (above the subject ID on the top left) to go back to the subjects index page. You should then see all the previous search filters still in place.
Badge
Breadcrumbs
Search …
=> Indexes Design Notes

src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPane.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.spec.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.spec.js
Closes #133 
When a transcription is approved, and the UI is disabled, a user should not be able to click a reduction line to open the transcription pane.
=> Disable Line Clicking if Transcription Approved

src/__snapshots__/Storyshots.test.js.snap, src/components/Badge/BadgeContainer.js, src/components/Badge/BadgeContainer.spec.js, src/components/Modals/SubjectLockedModal/SubjectLockedModal.js, src/components/Modals/SubjectLockedModal/SubjectLockedModalContainer.js, src/components/Modals/SubjectLockedModal/SubjectLockedModalContainer.spec.js, src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js, src/screens/SubjectsIndex/SubjectsPageContainer.js, src/screens/SubjectsIndex/SubjectsPageContainer.spec.js, src/screens/SubjectsIndex/table.js, src/store/AuthStore.js, src/store/AuthStore.spec.js, src/store/ClientStore.spec.js, src/store/Reduction.js, src/store/Reduction.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Closes #26 
Refer to [this doc](https://docs.google.com/document/d/1aBMwZM6X0wf-K0fkE0JPX9h_DHjj_hOBDCJzhJLx3ig/edit) for a bit more backend and frontend info. 
**Use case:**
For the text editor app, we don't want two people to be editing a transcription at the same time. Because of that, transcriptions have a `locked_by` attribute that is set to the person who is currently accessing a transcription. If you try to update a transcription that is `locked_by` another user, the `PATCH` (that occurs when attempting to update) will error, so that is a situation we want to avoid. **Important:** A user can lock a subject for three hours.
Most importantly, after a user finishes editing a transcription, that user should unlock a transcription by hitting an endpoint `/transcriptions/:id/unlock`, and …
=> Transcription Locking and Unlocking

src/store/SearchStore.js, src/store/SearchStore.spec.js
The search modal was incorrectly pinging the TOVE db for `subject_id`, which doesn't exist. Instead, `id` should work here since TOVE transcription IDs map exactly to Panoptes subjects
=> Fix bug when searching by Zooniverse id

src/__snapshots__/Storyshots.test.js.snap, src/theme.js
Closes #139 
This PR gives hover states to all buttons. Visually, hover states should be the same as focus states and they should not occur when a button is disabled.
=> Button hover state

src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Oops, looks like the extracts were borked at some point and aren't showing the correct transcription time (see below). This turned out to be an issue with the data saved correctly in the store.
=> Allow Transcription Dates to Appear

src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/Title/Title.js, src/components/ResourcesTable/ResourcesTable.js, src/components/ResourcesTable/ResourcesTable.spec.js
This PR just fixes three UI issues:
- Allows the title/breadcrumb component to wrap on narrow screens fixing a problem on all browsers (fig 1)
- Fixes a Firefox transcription table overflow issue (fig 2)
- Fixes a Safari issue where the metadata close button to the right of container isn't present (fig 3)
Closes #146 
_Fig 1_
_Fig 2_
_Fig 3_
You can see the current issues at [alice.preview.zooniverse.org](alice.preview.zooniverse.org)
=> Fix Inconsistencies Between Browsers

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.spec.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableContainer.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/mockData.js, src/components/FilmstripViewer/FilmstripViewer.js, src/components/FilmstripViewer/FilmstripViewer.spec.js, src/components/FilmstripViewer/FilmstripViewerContainer.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.spec.js, src/components/FilmstripViewer/components/FilmstripThumbnail/ThumbnailBorder.js, src/components/LineViewer/LineViewerContainer.js, src/components/LineViewer/LineViewerContainer.spec.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPane.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.spec.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.js, src/components/SubjectViewer/components/AnnotationsPane/SVGLines.spec.js, src/helpers/isEqual.js, src/helpers/isEqual.spec.js, src/helpers/parseTranscriptionData.js, src/helpers/slopeHelpers.js, src/helpers/slopeHelpers.spec.js, src/screens/Editor/Editor.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Closes #95 
[Invision Design](https://projects.invisionapp.com/d/#/console/17925240/371813757/preview) - note the blue outline is outdated
In a nutshell, this PR does two things:
- Shows all slope values for a given page, allows users to select different values, and denotes them when not 0 degrees
- Allows users to rearrange the order of these slope frames and saves the resulting order
There were many gotchas when writing this PR, but they _should_ all be resolved:
- Will the page order be rearranged to the original values when choosing to "edit aggregation settings" back to the original values? (default values under DB SCAN)
- Will the transcription retain frame order when reloading the transcription
- Will the UI show when frames with the same page number are grouped together?
- Can a …
=> Rearrange Pages By Slope Values

src/App.js, src/App.test.js, src/helpers/mockJWT.js, src/helpers/mockJWT.spec.js, src/store/ClientStore.js, src/store/ProjectsStore.js, src/store/ProjectsStore.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js, src/store/WorkflowsStore.js, src/store/WorkflowsStore.spec.js
As we know from ASM, Panoptes tokens will expire after two hours. The difference between this app and ASM is that we're using auth here, where we used oauth in ASM. Oauth needed a redirect to allow a bearer token refresh. Auth does not require a redirect, so we can refresh the token staying in the same spot.
However, all calls need to be wrapped in a bearer token check to make sure we always have a valid token and are sending that back to TOVE. This PR should handle all of that. However, depending on when this merges, I'll have to update other open PRs to use this sort of wrapper around outgoing TOVE calls.
Closes #82
=> Avoid Two hour timeout

src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
I believe this should take care of the subject locking issue that was first identified in #158 
I believe `null` values were being interpreted as a transcription being locked. The check was:
- See if the current transcription's `locked_by` equals the current user
- If it does not equal, show the locked modal
What if `locked_by` is `null`, meaning it is available/unlocked?
- Check if `null` equals the current user
- It isn't equal, show the locked modal
This doesn't make sense!
This PR should rectify that issue by checking instead if the transcription is locked by a **different** user and responding accordingly. I'm not positive it should work, as I wasn't able to replicate the issue, but it should take care of what I believe the issue to be.
=> Test for Transcription Locked By Different User

src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/MetadataButton/MetadataButton.spec.js, src/components/EditorHeader/components/MetadataButton/MetadataButtonContainer.js, src/components/EditorHeader/components/MetadataButton/mockMetadata.js, src/helpers/gsCountFromExtracts.js, src/helpers/gsCountFromExtracts.spec.js
Closes #163 
Upon an initial audit, I noticed the metadata needed cleaning. More info in the associated issue, but this also depended on bringing a bit more transcription data into the modal.
=> Adjust Metadata Modal

src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.spec.js, src/components/SubjectViewer/components/AnnotationsPane/AnnotationsPaneContainer.js, src/helpers/parseTranscriptionData.js, src/store/Reduction.js, src/store/TranscriptionsStore.js
There were a few bugs with extracts that this PR aims to fix:
- Add extracts lines back to the subject (erroneously removed in #158)
- Fix several issues with adjusting frames with sub-keys (ex: `frame0.0`, `frame0.1`, etc.)
- Allow lines to be added
- Allow lines to be deleted
- Allow lines to be reordered
=> Fix Issues with Extracts

src/__snapshots__/Storyshots.test.js.snap, src/components/FilmstripViewer/FilmstripViewer.js, src/components/ResourcesTable/ResourcesTable.js, src/components/StepNavigation/StepNavigation.js, src/components/StepNavigation/StepNavigation.spec.js, src/screens/SubjectsIndex/SubjectsPageContainer.js, src/screens/SubjectsIndex/SubjectsPageContainer.spec.js, src/theme.js
This fixes an issue with pagination on the transcriptions container. What was once appearing as this:
Should now look like this (apologize for the quick scrolling in the video):
=> Fix Subjects Page Pagination Issue

src/screens/SubjectsIndex/table.js
This is a quick change to fix the headers of the subjects page container based on a recent call. To match the following:
Original headers:
The new header reads "Low Consensus Lines," whereas before it read "Consensus Score," but was pretty vague and was basically a fraction of `low_consensus_lines/transcribed_lines`. The following column already includes "Transcribed Lines," so listing it twice was redundant.
=> Adjust Subjects Page Container Headers

src/store/TranscriptionsStore.js
This PR fixes one bug with the undo button. 
**The problem:**
Sometimes, pressing the undo button would transform the transcription state unexpectedly. For example, you may press the undo button and see a transcription consensus text does not match the transcription options given in the line. 
_How to replicate this:_
- Try rearranging the rows of a transcription several times. Press the undo button a few times to visit a past state. Maybe try to open a transcription line a couple times to really throw off the state. Eventually, you'll see some consensus text that doesn't match the options given.
- You can also break the editor if you:
- Change the page (clicking on a new image on the filmstrip viewer at the bottom of the page)
- Press the undo button to go back to the previous page
- …
=> Remember Parsed Extracts (Undo Button Bug)

src/__snapshots__/Storyshots.test.js.snap, src/components/EditorHeader/components/MetadataButton/MetadataButton.js, src/components/EditorHeader/components/MetadataButton/MetadataButtonContainer.spec.js, src/components/FilmstripViewer/FilmstripViewer.js, src/components/FilmstripViewer/FilmstripViewerContainer.js, src/components/FilmstripViewer/FilmstripViewerContainer.spec.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.js, src/components/FilmstripViewer/components/FilmstripThumbnail/FilmstripThumbnail.spec.js, src/components/SearchModal/SearchModal.js, src/helpers/status.js, src/store/SearchStore.js, src/store/SearchStore.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
This PR addresses an item in #165. Once a subject is approved, volunteers shouldn't be able to make any edits. That includes rearranging pages. There is also a bit of refactoring here. The PR covers several items:
- When transcription is approved, disable rearranging pages
- When subject is not approved, show a "move" cursor when hovering over a filmstrip thumbnail
- Refactoring: Abstract out all "status" strings into a single file.
=> Disable Filmstrip Thumbnail Reordering with Approved Subjects

src/components/SubjectViewer/SubjectViewerContainer.js
This PR shows the zoom and rotate tools at all times. Previously, the tools were disabled when the modal was open to edit a line.
=> Show Zoom/Rotate Tools with Active Line

src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js
From Slack:
PAN/ZOOM DOESN'T RESET ON CHANGING SUBJECTS
- Pan/Zoom resets correctly when changing pages of a Subject, but not when changing to a different Subject.
Image position (scale, translateX, translateY) now changes on `Editor` unmount, or whenever someone navigates away from the editor page.
=> Reset Image Position on Subject Change

src/__snapshots__/Storyshots.test.js.snap, src/components/FilmstripViewer/FilmstripViewer.js, src/components/FilmstripViewer/FilmstripViewer.spec.js, src/components/FilmstripViewer/FilmstripViewerContainer.js
Closes #177 
Supersedes #178 
Following up on the issue above, the Flimstrip Viewer doesn't have any reason to open and collapse as a panel. This will also help with some of the display discrepancies in the viewer. 
I've also adjusted the tests here a bit. We really shouldn't be mocking out `React.useState`. I erroneously did this with I first started using hooks, but mocking the function keeps React from performing as it naturally does and leads to irregular tests. Removing the mock here allows the tests to respond to state changes when using `mount`, which also improved coverage.
=> Remove Filmstrip Open/Close Functionality

src/__snapshots__/Storyshots.test.js.snap, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTable.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js, src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.spec.js
Closes #189 
Following up on a conversation in the issue above, this PR gives an ending ellipsis to long text rows. It also attached drag handlers to the transcription row text to further try to avoid the issue seen above. I believe there's an edge case where the same bug can occur when the mouse is held at the border between two rows.
=> Fix Bug When Reordering Rows of Different Heights 

package.json, src/components/Badge/BadgeContainer.js, src/components/Badge/BadgeContainer.spec.js, src/screens/Editor/Editor.js, src/screens/Editor/Editor.spec.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Closes #179 
This PR fixes the issue mentioned above and also handles a few more issues:
- Refactors the code by changing `lockedByDifferentUser` to `lockedByCurrentUser`. 
- I know this has gone both ways in the past, but I now think `lockedByCurrentUser` makes for a cleaner conditional
- Refactor some of the testing in the `TranscriptionsStore`
- Initially, that store set up the primary "fetch transcription" test as retrieving a transcription you were locked out of. This is more of an edge case and should be separated into a different `describe` block.
=> Fix Logout Crash on Editor Page

src/components/LineViewer/LineViewer.js, src/components/LineViewer/LineViewer.spec.js
Taken from #165 
This PR closes the `LineViewer` (Selected transcription) modal when pressing the escape key. Tests are included.
=> Press Escape to Close Selected Transcription

src/components/AggregatedTranscriptions/components/TranscriptionTable/TranscriptionTableRow.js
Closes #192 
Quick fix to handle transcriptions appearing squeezed together when many exist.
=> Give transcription rows a minimum height

src/components/EditorHeader/components/HeaderButton/DownloadSetDataContainer.js, src/components/Modals/DownloadDataModal/DownloadDataModal.js, src/components/Modals/DownloadDataModal/DownloadDataModal.spec.js
Closes #195 
Parts of the app still refer to "groups" as "subject sets." Although they are somewhat similar, we're trying to make a distinction between the two here. 
Panoptes uses the term "subject sets" to refer to a collection of subjects that a workflow can reference. This may be a collection of images from a certain time period, a collection of subjects from a particular work, whatever grouping method is preferred. 
ALICE allows subjects to be grouped differently using a `group_id` field defined on each subject. This can help researchers find subjects in ALICE using that `group_id` field when searching. This was preferred so institutions could defined the `group_id` value using a value known within the institution and defining that value in the metadata before uploading the subjects …
=> Refer to subject sets as groups

src/__snapshots__/Storyshots.test.js.snap, src/components/FilmstripViewer/FilmstripViewer.js, src/components/Modals/DeletePageModal/DeletePageModal.js, src/components/Modals/DeletePageModal/DeletePageModalContainer.js, src/components/Modals/DeletePageModal/content.js, src/helpers/slopeHelpers.js, src/store/TranscriptionsStore.js
For clarification:
**frame** means the different images of a multi-image subject
**page** means the different options available via the filmstrip viewer
Some errors existed with the page deletion functionality. Including:
- When deleting the final instance of a **page** without a duplicate **frame**, the **page** should still remain active
- Copy on the Delete Page modal should be different if you're deleting the final **page** that doesn't have a **frame** duplicate
- After deleting a **page** the transcription should be saved
- Deleting the final line of a **page** should delete the entire **page** if **frame** duplicates exist
- Previously, if we deleted a **page** that didn't have any **frame** duplicates, then we deleted another **page**, that previous **page** would disappear. That …
=> Troubleshoot Page Deletion

src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.js, src/screens/ProjectsIndex/components/ProjectCard/ProjectCard.spec.js
closes #207 as the API now returns the project image avatar URL with the scheme (https) we can use this instead of `//` relative URL from the domain.
=> fix project avatars image src

.github/workflows/run_tests.yml
Building the production static assets is unnecessary for test running.
=> Remove unnecessary build

src/components/EditorHeader/components/Title/Title.js, src/components/EditorHeader/components/Title/Title.spec.js, src/components/Modals/DownloadDataModal/DownloadDataModalContainer.js, src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Related to issue https://github.com/zooniverse/alice/issues/233
Changes made to tove (currently deployed in staging but not in prod yet), is to send over within `meta` field of the response body of `/transcriptions` call a new attribute called `approved_count` which calculates the number of approved transcriptions that come in from the api call out of all the records queries from the call. 
NOTE (to self) : Before deploying to production, must deploy tove changes to prod first.
=> Fix approved total number

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
MS issued a breaking change in a new version of the az client used by our CI tooling: https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli
This PR includes the `--overwrite` flag on all `az storage blob upload-batch` commands. This change should be ported to the shared ci-cd repo and this repo migrated when this is proven to work, also.
=> Include newly-required --overwrite flag in az uploads

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
michelle++
`--overwrite` is supposedly sufficient according to the related `az` issue, but if this still complains, I'll update it to `--overwrite true`.
=> Typo: add missing backslashes

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
The new version of the Azure CLI's `az storage blob upload` function doesn't properly detect the content type of .html or .txt files after their recent update. JS/css and media files seem unaffected, perhaps because they're using the `az storage blob upload-batch` function instead. Rather than pinning an old version, for now I'm going to ensure that specifying these types is sufficient and open an issue on their repo.
=> Specify content-type of text/html files

src/screens/About/About.js, src/screens/About/VideoTutorials.js, src/screens/About/VideoTutorials.spec.js, src/screens/About/components/VimeoEmbed.js, src/screens/About/components/VimeoEmbed.spec.js, src/screens/About/contents.js
Closes #253.
Adds video tutorials noted in linked issue to a new About page Video Tutorials section, with VimeoEmbed component. Video titles are listed in and linked in side menu bar (src/screens/About/contents.js).
Section description currently placeholder text, to be edited or deleted.
=> Add Video Tutorials section to about page

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
This app uses yarn for building, so I left that part alone and stored the build artifact. The deploy_static and slack_notification workflows can be shared, though.
=> Use shared workflows for deploy & notification

.storybook/main.js, package.json, yarn.lock
`@storybook/preset-create-react-app` is recommended with Storybook 5.3, and required for Storybook 6+.
=> Add @storybook/preset-create-react-app

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml, package.json, yarn.lock
Bump `react-scripts` from [3.0.1](https://github.com/facebook/create-react-app/blob/main/CHANGELOG-3.x.md#301-2019-05-08) to [3.4.4](https://github.com/facebook/create-react-app/blob/main/CHANGELOG-3.x.md#344-2020-10-20)
Includes several bug fixes and security patches for build tools. As noted in the [`react-scripts` changelog](https://github.com/facebook/create-react-app/blob/main/CHANGELOG-3.x.md), these vulnerabilities do not affect Create React App projects.
Fix job names in the deploy Slack notifications.
=> Bump `react-scripts` to 3.4.4

.storybook/main.js, README.md, package.json, src/components/SubjectViewer/components/SVGView/SVGView.js, yarn.lock
- allow local development to use `https://local.zooniverse.org`.
- update the README for local development.
- Fix `useState` in `SVGView`. Hooks can't appear after conditional returns.
- Remove legacy Storybook config (from Storybook 3, I think.)
=> Add HTTPS for development and tidy up legacy code

package.json, yarn.lock
Bump all the storybook packages from 5.3 to 6.4. Pin `babel-loader` and `webpack` to versions that are compatible with `react-scripts`.
=> Bump Storybook to 6.4.21

src/store/TranscriptionsStore.js, src/store/TranscriptionsStore.spec.js
Store the `lockedBy` username when a page is locked. Fixes a bug where the ‘locked’ modal opens but the username is empty, preventing you from seeing who has the page open for editing. See the screenshot in #329.
=> Show the username for locked pages

package.json, yarn.lock
This is a dependency bump, replacing #349 . (Thanks for giving more work, dependabot!)
- `@storybook/react` and `@storybook/addon-*` deps have been updated to 6.5.10
- `@storybook/preset-create-react-app` REMAINS at `~3.2.0`, since the next version, 4.x, requires Create React App v5 or higher. Which is a problem, because attempts to update to `react-scripts` 5.x results in broken tests. (Dependabot attempt: #318 ; human attempt: #308 .)
Testing: `yarn storybook` runs fine, and I'm able to view all 14 Stories on localhost. Each Story's tested component seems to function similarly as on `master`
Going ahead and merging this, to get Dependabot off our back.
=> Maintenance: update storybook sub/dependencies to 6.5.10

package.json, yarn.lock
#317 pinned `webpack` and `babel-loader` to fixed versions, but those shouldn't be necessary any more.
=> Remove webpack and babel-loader overrides

src/store/ProjectsStore.js
Increase the page size for projects and project roles queries to match the number of project IDs included in each query.
- closes #597.
- closes #330.
=> Increase the page size for projects queries
